config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
	get 'process' => 'orders#processing'
	get 'resolve/:id' => 'bees#resolve'
  resources :bees, only: [:show,:index]
  resources :orders, only: [:new, :create]
  resources :order_all, only: [:new, :create]
  resources :all_store, only: [:index]
  resources :store, only: [:show]

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_all
	belongs_to :item
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	include SplitHelper

  def new
    @order_all = OrderAll.new
    @items = Item.all
		@items.each do |item|
			@order_all.orders.build(:item_id => item.id) #prepopulate item id
		end
  end

  def create
		#flash[:notice] = "asdf"
		#@test = params[:new_order_all][:orders_attributes]
		#flash[:notice] = @test.to_str()
    @order_all = OrderAll.new(order_all_params)
		puts params[:order_all][:orders_attributes]["0"][:quantity]
		params[:order_all][:orders_attributes].each do |order|
			if order[1][:quantity].to_i() <= 0
				@order_all.orders[order[0].to_i()].destroy #delete record to prevent redundant rows
			end
		end
		
    if @order_all.save
      flash[:notice] = "Sucessfully Added New Order!"
      redirect_to root_path
    else
      flash[:notice] = "Failure in Creating New Order!"
      render :new
    end
  end
	
	def processing #processes floating orders
		puts 'PROCESSING...'
		splitMain()
	end

  private

  def order_all_params
    params.require(:order_all).permit(:delivery_time, :address, orders_attributes: [ :item_id, :quantity ])
  end
end

app/views/orders/new.html.slim
.row.top-row
    h1 Order Form
.container

  /= simple_form_for :something, :url => new_order_path do |f|
  /  = f.input :delivery_time, input_html: {class: 'form-control'}
  /  = f.input :quantity, input_html: {class: 'form-control'}
  /  = f.input :something, input_html: {class: 'form-control'}

  .font
    = form_for @order_all, url: orders_path do |f|
      = f.label "Delivery Time: "
      = f.datetime_local_field :delivery_time, :value => DateTime.now.strftime("%Y-%m-%dT%H:00:00")
	  br
	  = f.label "Delivery Address: "
	  = f.text_field :address
      br
      = f.label "Select Items: "

	  = f.fields_for :orders do |order|
        ul
		  li
			= Item.find(order.object.item_id).name + ' x '
			= order.hidden_field :item_id, :value => order.object.item_id
		    = order.number_field :quantity
      = f.submit "Submit", class: 'button2 button2hover'
	  = link_to "Cancel", root_path, class: 'button2 button2hover'

app/views/orders/processing.html.slim
.row.top-row
    .col-sm-6
      h1 beesplit
      h2 Ensuring fair split on your bee's workloads :)
.container
	well
	  ul
		== flash[:process]
	h2 Processed Orders
	.table
	  .tablefont
		table.table.table-striped
		  thead
			tr
			  th Order_All Id
			  th Delivery Time
			  th Address
			  th Bee Assigned
			  th Details
		  tbody
			- @order_alls_processed.each do |row|
			  tr
				td = row.id
				td = row.delivery_time
				td = row.address
				- if row.bee_id.nil?
				  td = "-Splitted-"
				- else
				  td = link_to Bee.find(row.bee_id).name, Bee.find(row.bee_id)
				td
				  table.table.table-striped
					thead
					  tr
						th Order Line Id
						th Item
						th Price
						th Quantity
						th Category
					tbody
					  - row.orders.each do |order|
						tr

						  td = order.id
						  td = order.item.name
						  td = order.item.price
						  td = order.quantity
						  td = order.item.category
	h2 Pending Orders
	.table
	  .tablefont
		table.table.table-striped
		  thead
			tr
			  th Order_All Id
			  th Delivery Time
			  th Address
			  th Details
		  tbody
			- @order_alls_unprocessed.each do |row|
			  tr
				td = row.id
				td = row.delivery_time
				td = row.address
				td
				  table.table.table-striped
					thead
					  tr
						th Order Line Id
						th Item
						th Price
						th Quantity
						th Category
					tbody
					  - row.orders.each do |order|
						tr

						  td = order.id
						  td = order.item.name
						  td = order.item.price
						  td = order.quantity
						  td = order.item.category
	button = link_to "Home", root_path

app/views/orders/show.html.slim
.container
  .row
    h1 = "#{@bee.name}'s Orders"
  .table
    .tablefont
      table.table.table-striped
        thead
          tr
            th Order Id
            th Item
            th Price
            th Category
        tbody

          - @bee.orders.each do |order|
            tr

              td = order.id
              td
                table
                  - Item.find(order.item_id) do |item|
                    tr
                      td = item.name
              td
                table
                  - Item.find(order.item_id) do |item|
                    tr
                      td = item.price
              td
                table
                  - Item.find(order.item_id) do |item|
                    tr
                      td = item.category